backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Meta description", name: "meta_description", widget: "string"}
        - { label: "Header first line", name: "header_first_line", widget: "string"}
        - { label: "Header second line", name: "header_second_line", widget: "string"}
        - { label: "Header third line", name: "header_third_line", widget: "string"}
        - { label: "About", name: "about", widget: "markdown"}
        - label: "Portrait"
          name: "portrait"
          widget: "image"
          choose_url: true
        - label: 'Socials'
          name: "socials"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Link", name: "link", widget: "string"}
        - label: 'Academy projects'
          name: "academy_projects"
          widget: list
          fields:
            - { label: "Discription", name: "description", widget: "text"}
        - label: 'Art projects'
          name: "art_projects"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - label: "Image"
              name: "image"
              widget: "image"
              choose_url: true
              required: false
            - { label: "Discription", name: "description", widget: "text", required: false}
        - label: 'Skills'
          name: "skills"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Discription", name: "description", widget: "text"}
        - label: 'Principles'
          name: "principles"
          widget: list
          fields:
            - { label: "Discription", name: "description", widget: "text"}
            