backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Header first line", name: "header_first_line", widget: "string"}
        - { label: "Header second line", name: "header_second_line", widget: "string"}
        - { label: "Header third line", name: "header_third_line", widget: "string"}
        - { label: "About", name: "about", widget: "text"}
        - label: "Portrait"
          name: "portrait"
          widget: "image"
          choose_url: true
        - label: 'Socials'
          name: "socials"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Link", name: "link", widget: "string"}
        - label: 'Projects'
          name: "projects"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - label: "Image"
              name: "image"
              widget: "image"
              choose_url: true
            - { label: "GitHub link", name: "github", widget: "string", required: false}
            - { label: "Preview link", name: "preview", widget: "string", required: false}
            - label: 'Stack'
              name: "stack"
              widget: list
              required: false
              fields:
                - { label: "Name", name: "name", widget: "string"}
                - { label: "Icon link", name: "icon", widget: "string"}
            - { label: "Discription", name: "description", widget: "text"}
        - label: 'Skills'
          name: "skills"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Discription", name: "description", widget: "text"}